# Generated by Django 3.2 on 2023-04-04 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('secondname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30)),
                ('ward', models.CharField(choices=[('FEMALEMEDICALWARD', 'FEMALE MEDICAL WARD'), ('MALEMEDICALWARD', 'MALE MEDICAL WARD'), ('SURGICAL WARD', 'SURGICAL WARD'), ('MARTERNITY WARD', 'MARTERNITY WARD'), ('FEMALEMEDICALWARD', 'FEMALE MEDICAL WARD'), ('PAEDIATRICS', 'PAEDIATRICS')], max_length=30)),
                ('bedno', models.CharField(max_length=30)),
                ('fileno', models.CharField(max_length=30)),
                ('dateofadmission', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-dateofadmission',),
            },
        ),
    ]
