# Generated by Django 3.2 on 2023-04-06 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inpatient', '0002_alter_admission_ward'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admission',
            name='secondname',
        ),
    ]
