# Generated by Django 3.2 on 2023-01-24 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookclinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30)),
                ('tcadate', models.DateField(blank=True, null=True)),
                ('clinic', models.CharField(choices=[('GOPC', 'GOPC'), ('POPC', 'POPC'), ('SOPC', 'SOPC'), ('MOPC', 'MOPC'), ('ENT', 'ENT'), ('ORTHOPAEDIC', 'ORTHOPAEDIC'), ('ONCOLOGY', 'ONCOLOGY'), ('OPTICAL', 'OPTICAL'), ('COLONOSCOPY', 'COLONOSCOPY'), ('ENDOCOPY', 'ENDOSCOPY'), ('DENTAL', 'DENTAL')], max_length=30)),
                ('doctornote', models.TextField(max_length=100)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-tcadate',),
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=500)),
                ('lastname', models.CharField(max_length=500)),
                ('idno', models.CharField(max_length=500)),
                ('phone', models.CharField(max_length=500)),
                ('oureachlocation', models.CharField(max_length=500)),
                ('dx', models.CharField(max_length=500)),
                ('followup', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=500)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
    ]
