# Generated by Django 3.2 on 2023-02-16 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booktheatre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30)),
                ('dateofoperation', models.DateField(blank=True, null=True)),
                ('typeofoperation', models.CharField(choices=[('Caesarean_Section', 'Caesarean_Section'), ('General_Surgery', 'General_Surgery'), ('Thoracic_Surgery', 'Thoracic_Surgery'), ('Colon_and_Rectal_Surgery', 'Colon_and_Rectal_Surgery'), ('DENTAL', 'DENTAL')], max_length=30)),
                ('doctornote', models.TextField(max_length=100)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-dateofoperation',),
            },
        ),
    ]
