# Generated by Django 3.2 on 2023-02-16 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0002_booktheatre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booktheatre',
            name='doctornote',
        ),
        migrations.AddField(
            model_name='booktheatre',
            name='doctor',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
