# Generated by Django 3.2 on 2023-08-12 17:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('RAD', 'Radiology'), ('CARD', 'Cardiology'), ('SURG', 'Surgery'), ('LAB', 'Laboratory')], max_length=4)),
                ('name', models.CharField(max_length=100)),
                ('state', models.CharField(choices=[('Operational', 'Operational'), ('Maintenance', 'Maintenance'), ('Other', 'Other')], max_length=20)),
                ('in_charge', models.CharField(max_length=100)),
                ('unique_identifier', models.CharField(max_length=20, unique=True)),
                ('date_registered', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
