# Generated by Django 3.2 on 2022-10-26 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_auto_20221024_1403'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PatientIdUpload',
        ),
    ]
