# Generated by Django 3.2 on 2022-12-31 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_delete_patientidupload'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newid',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterField(
            model_name='newid',
            name='patientid',
            field=models.FileField(upload_to='images/%Y/%m/%d'),
        ),
    ]
