# Generated by Django 3.2 on 2022-02-25 12:49

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aboutpage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('content', models.TextField(blank=True, max_length=700)),
                ('image', models.URLField(blank=True, max_length=350)),
                ('image1', models.URLField(blank=True, max_length=350)),
                ('aboutus', models.TextField(blank=True, max_length=500)),
                ('aboutimage', models.URLField(blank=True, max_length=350)),
                ('story', models.TextField(blank=True, max_length=1500)),
                ('storyimage', models.URLField(blank=True, max_length=350)),
                ('team', models.TextField(blank=True, max_length=1500)),
                ('teamimage', models.URLField(blank=True, max_length=350)),
                ('whyus', models.TextField(blank=True, max_length=1500)),
                ('whyusimage', models.URLField(blank=True, max_length=350)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=200)),
                ('content', models.TextField(max_length=300)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Homepage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('content', models.CharField(blank=True, max_length=700)),
                ('image', models.URLField(blank=True, max_length=350)),
                ('title1', models.CharField(max_length=500)),
                ('content1', models.CharField(blank=True, max_length=700)),
                ('image1', models.URLField(blank=True, max_length=350)),
            ],
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=500)),
                ('second_name', models.CharField(max_length=500)),
                ('phone_number', models.IntegerField(blank=True, max_length=15)),
                ('file_number', models.IntegerField(blank=True, max_length=500)),
                ('age', models.IntegerField(blank=True, max_length=3)),
                ('id_number', models.IntegerField(blank=True, max_length=50)),
                ('patient_category', models.CharField(blank=True, max_length=500)),
                ('file_identity', models.CharField(default=home.models.generateUUID, editable=False, max_length=6, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
