# Generated by Django 3.2 on 2022-04-11 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20220317_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('first_name', models.CharField(max_length=15)),
                ('second_name', models.CharField(max_length=15)),
                ('phone_number', models.IntegerField(blank=True)),
                ('age', models.IntegerField(blank=True)),
                ('id_number', models.IntegerField(blank=True)),
                ('patient_category', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file_no', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
