# Generated by Django 3.2 on 2022-04-20 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_new'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField()),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='apointment',
            options={'ordering': ['-accepted_date']},
        ),
        migrations.AddField(
            model_name='apointment',
            name='file_number',
            field=models.IntegerField(blank=True, default=False),
        ),
    ]
