# Generated by Django 3.2 on 2023-01-30 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_post_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
