# Generated by Django 3.2 on 2023-04-04 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_post_id_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssociatedPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associated_posts', to='home.post')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
