"""
Django settings for system project.

Generated by 'django-admin startproject' using Django 3.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
#from decouple import config

import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-avm2k&r6z#d4y^r2fg_5)gq9t49&b=!tt@$4qcll4w20sspink'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*','192.168.1.35','192.168.1.45','192.168.1.50','192.168.1.63','192.168.1.46','192.168.1.55','127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django_windows_tools',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    #'haystack',
    'crispy_forms',
    'home',
    'records',
    'outreach',
    'inventory',
    
    #'homee',
    #'django_plotly_dash.apps.DjangoPlotlyDashConfig',
    'channels',
    'images',
    'inpatient'
    #'channels_redis'
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'system.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            # Absolute path of your TEMPLATE_DIR
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'system.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



LOGIN_REDIRECT_URL = '/login'


#STATIC_URL = '/static/'

MEDIA_URL ='/media/'

CRISPY_TEMPLATE_PACK = 'bootstrap4'


#STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')


###
#django_heroku.settings(locals())


#Sending emails
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
#EMAIL_HOST_USER = config("EADDRESS")
#EMAIL_HOST_PASSWORD = config("EPASSWORD")

#HAYSTACK_CONNECTIONS = {
 #   'default': {
 #       'ENGINE': 'haystack.backends.elasticsearch5_backend.Elasticsearch5SearchEngine',
 #       'URL': 'http://192.168.1.104:8000/',
 #       'INDEX_NAME': 'haystack',
 #   },
#}

# Add CHANNEL_LAYERS
##   'default': { 'BACKEND': 'channels_redis.core.RedisChannelLayer',
 #               'CONFIG': {
 #                          'hosts': [('127.0.0.1')]
#                          }
 #             }
#}


#Add STATICFILES_FINDERS 
#STATICFILES_FINDERS = [
    
#    'django_plotly_dash.finders.DashAssetFinder',
#    'django_plotly_dash.finders.DashComponentFinder'
#]

#Add PLOTLY_COMPONENTS
#PLOTLY_COMPONENTS = [
#   'dash_core_components',
 #   'dash_html_components',
 #   'dash_renderer',
 #   'dpd_components'
#]

#Add X_FRAME_OPTIONS = 'SAMEORIGIN' to settings.py to enable frames within HTML documents
X_FRAME_OPTIONS = 'SAMEORIGIN'

ASGI_APPLICATION = 'system.routing.application'