# Generated by Django 3.2 on 2022-10-25 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(max_length=500)),
                ('image1', models.ImageField(null=True, upload_to='posts/%Y/%m/%d')),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
