# Generated by Django 3.2 on 2022-10-26 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_alter_post_image1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image1',
            field=models.ImageField(null=True, upload_to='posts/%Y/%m/%d'),
        ),
    ]
