# Generated by Django 3.2 on 2022-12-31 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_auto_20221029_0838'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-date',)},
        ),
    ]
